name: Daily Commit

on:
  schedule:
    # Runs at 02:00 UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git user 23f1002293@ds.study.iitm.ac.in
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "23f1002293@ds.study.iitm.ac.in"

      - name: Create empty commit and push
        run: |
          git commit --allow-empty -m "Automated daily commit"
          git push