name: Daily Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '22 8 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: 23f1002293@ds.study.iitm.ac.in
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit --allow-empty -m "Hello! Automated daily commit"
          git push
