name: Cache Speed Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 🧠 Cache dependencies
      - name: prime-cache-59561bd
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-59561bd
          restore-keys: |
            cache-

      # 🧩 Install dependencies (or simulate)
      - name: Install dependencies
        run: |
          pip install fastapi numpy --upgrade

      # 🧾 Echo cache hit/miss result
      - name: Check cache result
        run: echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
