name: Email Step Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: 23f1002293@ds.study.iitm.ac.in
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git commit --allow-empty -m "Hello! Automated daily commit"
          git push
